spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:p6spy:mysql://192.168.12.71/lz-cim?serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver


